version: '3.8'

services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.17.25
    container_name: es01
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - http.cors.enabled=true
      - http.cors.allow-origin="*"
    volumes:
      - data:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
    networks:
      - elastic

  elasticsearch_head:
    image: mobz/elasticsearch-head:2
    container_name: elasticsearch_head
    ports:
      - 9100:9100
    networks:
      - elastic

volumes:
  data:
    driver: local

networks:
  elastic:
    driver: bridge

